package dev.kadys.matchhub.moderation;
import dev.kadys.matchhub.error.NotFoundException;
import dev.kadys.matchhub.match.*;
import dev.kadys.matchhub.user.*;
import org.springframework.data.domain.*;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.util.UUID;
@Service public class ModerationService {private final ModerationReportRepository reports;private final UserRepository users;private final MatchRepository matches;public ModerationService(ModerationReportRepository reports,UserRepository users,MatchRepository matches){this.reports=reports;this.users=users;this.matches=matches;}@Transactional public ModerationDtos.Response create(ModerationDtos.CreateRequest request,UUID reporterId){User reporter=users.findById(reporterId).orElseThrow(()->new NotFoundException("Usuário não encontrado."));Match match=request.matchId()==null?null:matches.findById(request.matchId()).orElseThrow(()->new NotFoundException("Partida não encontrada."));return response(reports.save(new ModerationReport(reporter,match,request.reason().trim(),request.details().trim())));}@Transactional(readOnly=true) public Page<ModerationDtos.Response> list(ReportStatus status,Pageable pageable){return reports.findByStatusOrderByCreatedAtDesc(status,pageable).map(this::response);}@Transactional public ModerationDtos.Response update(UUID id,ReportStatus status){ModerationReport report=reports.findById(id).orElseThrow(()->new NotFoundException("Denúncia não encontrada."));report.setStatus(status);return response(report);}private ModerationDtos.Response response(ModerationReport report){return new ModerationDtos.Response(report.getId(),report.getReporter().getId(),report.getReporter().getName(),report.getMatch()==null?null:report.getMatch().getId(),report.getMatch()==null?null:report.getMatch().getTitle(),report.getReason(),report.getDetails(),report.getStatus(),report.getCreatedAt(),report.getResolvedAt());}}
